Add Auto-install for missing packages in bootstrap
Signed-off-by: deepssin <deepssin@redhat.com>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -89,8 +89,11 @@ if [ -n "$missing" ]; then
         $install_pkg $missing
     else
         echo "Please install missing packages or run './bootstrap install'"
-        echo "$install_pkg $missing"
-        exit 1
+        echo "$install_pkg $missing , going for automatic install..."
+        $install_pkg $missing || {
+            echo "Auto-install failed, exiting!!!"
+            exit 1
+        }
     fi
     fi
 
