bootstrap: add AlmaLinux and RockyLinux case
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -100,6 +100,27 @@ Linux)
             fi
         fi
         ;;
+    AlmaLinux|RockyLinux)
+       PYTHON=python3.12
+        deps=($PYTHON-pip $PYTHON-devel libev-devel libvirt-devel libffi-devel)
+        for package in ${deps[@]}; do
+          if ! rpm -q --whatprovides $package; then
+              missing="${missing:+$missing }$package"
+          fi
+        done
+        if [ -n "$missing" ]; then
+            echo "$0: missing required packages:" 1>&2
+            echo "$missing"
+            if [ "$install" = true ]; then
+                echo "Installing missing packages..."
+                sudo yum -y install $missing
+            else
+                echo "Please install missing packages or run './bootstrap install' if you have sudo"
+                echo "sudo yum -y install $missing"
+                exit 1
+            fi
+        fi
+        ;;
     Fedora|FedoraLinux)
        PYTHON=python3.12
         deps=($PYTHON-pip $PYTHON-devel)
