bootstrap: rewrite deps checking

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -27,174 +27,79 @@ if [ -z "$PYTHON" ]; then
   PYTHON=${PYTHON:-"python3"}
 fi
 
-case "$(uname -s)" in
-Linux)
-    if command -v lsb_release; then
-        OS=$(lsb_release --id --short)
-    else
-        . /etc/os-release
-        OS=$(echo $NAME | tr -d ' ')
-    fi
-    case "$OS" in
-    Ubuntu|Debian|LinuxMint)
-        deps=(qemu-utils python3-dev libssl-dev python3-pip python3-wheel $PYTHON-venv libev-dev libvirt-dev libffi-dev libyaml-dev)
-        for package in ${deps[@]}; do
-            if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
-                # add a space after old values
-                missing="${missing:+$missing }$package"
-            fi
-        done
-        if [ -n "$missing" ]; then
-            echo "$0: missing required packages:" 1>&2
-            echo "$missing"
-            if [ "$install" = true ]; then
-                echo "Updating metadata..."
-                sudo apt-get update
-                echo "Installing missing packages..."
-                sudo apt-get -y install $missing
-            else
-                echo "Please install missing packages or run './bootstrap install' if you have sudo"
-                echo "sudo apt-get -y install $missing"
-                exit 1
-            fi
+function check_dependencies {
+    case "$(uname -s)" in
+    Linux)
+        if command -v lsb_release; then
+            OS=$(lsb_release --id --short)
+        else
+            . /etc/os-release
+            OS=$(echo $NAME | tr -d ' ')
         fi
+        # rpm/dnf is the default (DRY)
+        has_pkg="rpm --whatprovides"
+        install_pkg="sudo dnf install -y"
+        case "$OS" in
+        Ubuntu|Debian|LinuxMint)
+            deps=(qemu-utils python3-dev libssl-dev python3-pip python3-wheel $PYTHON-venv libev-dev libvirt-dev libffi-dev libyaml-dev)
+            has_pkg="dpkg -C"
+            install_pkg="sudo apt install -y"
+            ;;
+        RedHatEnterpriseWorkstation|RedHatEnterpriseServer|RedHatEnterprise|CentOS)
+            deps=(python39-pip python39-devel mariadb-devel libev-devel libvirt-devel libffi-devel)
+            ;;
+        CentOSStream)
+            PYTHON=python3.12
+            deps=($PYTHON-pip $PYTHON-devel)
+            ;;
+        AlmaLinux|RockyLinux)
+            PYTHON=python3.12
+            deps=($PYTHON-pip $PYTHON-devel libev-devel libvirt-devel libffi-devel)
+            ;;
+        Fedora|FedoraLinux)
+            PYTHON=python3.12
+            deps=($PYTHON-pip $PYTHON-devel libev-devel libvirt-devel libffi-devel)
+            ;;
+        "openSUSE project"|"SUSE LINUX"|"openSUSE"|"openSUSELeap"|"openSUSETumbleweed")
+            PYTHON=python3.12
+            deps=(python312-pip python312-devel python312 libev-devel libvirt-devel libffi-devel)
+            install_pkg="sudo zypper install"
+            ;;
+        esac
         ;;
-    RedHatEnterpriseWorkstation|RedHatEnterpriseServer|RedHatEnterprise|CentOS)
-        deps=(python39-pip python39-devel mariadb-devel libev-devel libvirt-devel libffi-devel)
-        for package in ${deps[@]}; do
-          if ! rpm -q --whatprovides $package ; then
-              missing="${missing:+$missing }$package"
-          fi
-        done
-        if [ -n "$missing" ]; then
-            echo "$0: missing required packages:" 1>&2
-            echo "$missing"
-            if [ "$install" = true ]; then
-                echo "Installing missing packages..."
-                sudo yum -y install $missing
-            else
-                echo "Please install missing packages or run './bootstrap install' if you have sudo"
-                echo "sudo yum -y install $missing"
-                exit 1
-            fi
-        fi
-        ;;
-    CentOSStream)
-       PYTHON=python3.12
-        deps=($PYTHON-pip $PYTHON-devel)
-        for package in ${deps[@]}; do
-          if ! rpm -q --whatprovides $package ; then
-              missing="${missing:+$missing }$package"
-          fi
-        done
-        if [ -n "$missing" ]; then
-            echo "$0: missing required packages:" 1>&2
-            echo "$missing"
-            if [ "$install" = true ]; then
-                echo "Installing missing packages..."
-                sudo yum -y install $missing
-            else
-                echo "Please install missing packages or run './bootstrap install' if you have sudo"
-                echo "sudo yum -y install $missing"
-                exit 1
-            fi
-        fi
-        ;;
-    AlmaLinux|RockyLinux)
-       PYTHON=python3.12
-        deps=($PYTHON-pip $PYTHON-devel libev-devel libvirt-devel libffi-devel)
-        for package in ${deps[@]}; do
-          if ! rpm -q --whatprovides $package; then
-              missing="${missing:+$missing }$package"
-          fi
-        done
-        if [ -n "$missing" ]; then
-            echo "$0: missing required packages:" 1>&2
-            echo "$missing"
-            if [ "$install" = true ]; then
-                echo "Installing missing packages..."
-                sudo yum -y install $missing
-            else
-                echo "Please install missing packages or run './bootstrap install' if you have sudo"
-                echo "sudo yum -y install $missing"
-                exit 1
-            fi
-        fi
-        ;;
-    Fedora|FedoraLinux)
-       PYTHON=python3.12
-        deps=($PYTHON-pip $PYTHON-devel)
-        deps=($PYTHON-pip $PYTHON-devel libev-devel libvirt-devel libffi-devel)
-        for package in ${deps[@]}; do
-          if ! rpm -q --whatprovides $package; then
-              missing="${missing:+$missing }$package"
-          fi
-        done
-        fedora_release=$(lsb_release -rs)
-        package_manager=dnf
-        if [ $fedora_release -lt 23 ]; then
-            package_manager=yum
-        fi
-        if [ -n "$missing" ]; then
-            echo "$0: missing required packages:" 1>&2
-            echo "$missing"
-            if [ "$install" = true ]; then
-                echo "Installing missing packages..."
-                sudo $package_manager -y install $missing
-            else
-                echo "Please install missing packages or run './bootstrap install' if you have sudo"
-                echo "sudo $package_manager -y install $missing"
-                exit 1
-            fi
-        fi
-        ;;
-    "openSUSE project"|"SUSE LINUX"|"openSUSE"|"openSUSELeap"|"openSUSETumbleweed")
-	PYTHON=python3.12
-	deps=(python312-pip python312-devel python312 libev-devel libvirt-devel libffi-devel)
-	for package in ${deps[@]}; do
-            if ! rpm -q --whatprovides $package; then
-                if [ "$(rpm -q --whatprovides $package)" == "no package provides $package" ]; then
-                    missing="${missing:+$missing }$package"
-                fi
-            fi
-        done
-        if [ -n "$missing" ]; then
-            echo "$0: missing required packages, please install them:" 1>&2
-            echo "sudo zypper install $missing"
-            exit 1
-        fi
-        ;;
-    *)
-        echo "This script does not support your Linux distribution yet. Patches encouraged!"
-        exit 1
+
+    Darwin)
+        deps="python libvirt libev libffi"
+        has_pkg="brew list"
+        install_pkg="brew install"
         ;;
     esac
-    ;;
-Darwin)
-    if ! brew --version &>/dev/null; then
-        echo "You need Homebrew: http://brew.sh/"
-        exit 1
-    fi
-    for keg in python libvirt libev libffi; do
-        if brew list $keg >/dev/null 2>&1; then
-            echo "Found $keg"
-        else
-            if [ "$install" = true ]; then
-                brew install $keg
-            else
-                missing="${missing:+$missing }$keg"
-                echo "Please install missing packages or run './bootstrap install':"
-                echo "brew install $missing"
-                exit 1
-            fi
+    for package in ${deps[@]}; do
+        if ! $has_pkg $package &>/dev/null; then
+            # add a space after old values
+            missing="${missing:+$missing }$package"
+            echo missing=${missing}
         fi
     done
-    ;;
-*)
-    echo "This script does not support your OS yet. Patches encouraged!"
-    exit 1
-    ;;
-esac
+    debug=echo
+    if [ -n "$missing" ]; then
+        echo "$0: missing required packages:" 1>&2
+        echo "$missing"
+        if [ "$install" = true ]; then
+            # echo "Updating metadata..."
+            # sudo apt-get update
+            echo "Installing missing packages..."
+            echo $install_pkg $missing
+            # sudo apt-get -y install $missing
+        else
+            echo "Please install missing packages or run './bootstrap install'"
+            echo "$install_pkg $missing"
+            exit 1
+        fi
+    fi
+}
+
+check_dependencies
 
 PYTHON_BIN=$(command -v $PYTHON)
 if [ -z $PYTHON_BIN -o ! -e $PYTHON_BIN -o ! -x $PYTHON_BIN ]; then
@@ -225,12 +130,12 @@ if [ -z "$NO_CLOBBER" ] || [ ! -e $VENV ]; then
     $PYTHON_BIN -m venv $VENV
 fi
 
-source ./virtualenv/bin/activate
-
+source $VENV/bin/activate
+python3 -m pip install uv
 # First, upgrade pip
-$VENV/bin/pip install --upgrade pip
+# $VENV/bin/pip install --upgrade pip
 # Then, install uv
-$VENV/bin/pip install uv packaging
+# $VENV/bin/pip install uv packaging
 # From now on, use 'uv pip'
 PIP="$VENV/bin/uv pip"
 
@@ -244,7 +149,7 @@ if [ -f "$VENV/bin/ansible" ]; then
 fi
 
 # By default, install teuthology in editable mode
-$PIP install ${PIP_INSTALL_FLAGS:---editable '.[test]'}
+$PIP install --python $VENV/bin/python ${PIP_INSTALL_FLAGS:---editable '.[test]'}
 
 # Check to make sure requirements are met
 $PIP check
